vim.opt.relativenumber = true
vim.opt.nu = true
vim.opt.wrap = true
vim.opt.smartindent = true
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.swapfile = true
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile = true
vim.opt.termguicolors = true
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.autochdir = true
vim.g.netrw_banner = 0
vim.g.closetag_filenames = '*.html, *.xml, *.jsx, *.tsx, *.js'
vim.g.netrw_liststyle = 3
--vim.opt.colorcolumn = "80"
vim.opt.autochdir = true
vim.g.netrw_keepdir = 0
