- name: Install fedora packages
  dnf:
    name:
      - bat
      - brave-browser
      - code
      - composer
      - deja-dup
      - evolution
      - fd-find
      - firewall-config
      - fzf
      - gcc
      - gcc-c++
      - gimp
      - git
      - gnome-shell-extension-appindicator
      - golang
      - htop
      - inkscape
      - java-latest-openjdk
      - kernel-devel
      - lazygit
      - libappindicator-gtk3
      - libreoffice
      - mpv
      - ncdu
      - neovim
      - nodejs
      - parallel
      - php-cli
      - proton-vpn-gnome-desktop
      - python3-pip
      - python3-wheel
      - qbittorrent
      - ripgrep
      - ruby
      - seahorse-nautilus
      - sxiv
      - texlive-scheme-basic
      - tmux
      - virt-manager
      - vlc
      - weechat
      - zathura
      - zathura-pdf-mupdf
      - zsh
    state: latest

- name: Install pyenv
  become: true
  become_user: "{{ user }}"
  shell: curl https://pyenv.run | bash

- name: Install oh-my-zsh
  become: true
  become_user: "{{ user }}"
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended

- name: Install lf
  become: true
  become_user: "{{ user }}"
  shell: env CGO_ENABLED=0 GOPATH=/home/{{ user }}/.local/share/go go install -ldflags="-s -w" github.com/gokcehan/lf@latest

- name: Install packages from flatpak
  become: true
  become_user: "{{ user }}"
  community.general.flatpak:
    name:
      - com.discordapp.Discord
      - net.lutris.Lutris
      - io.dbeaver.DBeaverCommunity
      - us.zoom.Zoom
      - io.podman_desktop.PodmanDesktop
    state: present

- name: Install pnpm
  community.general.npm:
    name: pnpm
    global: true
    state: latest

- name: Set java jdk
  command: alternatives --set java java-latest-openjdk.x86_64

- name: Set defualt shell to zsh
  command: chsh -s /usr/bin/zsh "{{ user }}"

- name: Link zshrc to home folder
  become: true
  become_user: "{{ user }}"
  shell: ln -sf /home/{{ user }}/.config/zsh/.zshrc /home/{{ user }}/.zshrc

- name: Link zprofile to home folder
  become: true
  become_user: "{{ user }}"
  shell: ln -sf /home/{{ user }}/.config/zsh/.zshenv /home/{{ user }}/.zshenv
