- name: Install fedora packages
  dnf:
    name:
      - bat
      - brave-browser
      - deja-dup
      - evolution
      - filezilla
      - firewall-config
      - fzf
      - gcc
      - gcc-c++
      - git
      - gnome-shell-extension-appindicator
      - golang
      - htop
      - kernel-devel
      - lazygit
      - libappindicator-gtk3
      - libreoffice
      - ncdu
      - neovim
      - proton-vpn-gnome-desktop
      - python3-pip
      - python3-neovim
      - python3-wheel
      - remmina
      - ripgrep
      - seahorse-nautilus
      - sxiv
      - texlive-scheme-medium
      - tmux
      - transmission
      - virt-manager
      - virt-viewer
      - virt-install
      - vlc
      - zsh
    state: latest

- name: Install oh-my-zsh
  become: true
  become_user: "{{ user }}"
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended

- name: Install lf
  become: true
  become_user: "{{ user }}"
  shell: env CGO_ENABLED=0 GOPATH=/home/{{ user }}/.local/share/go go install -ldflags="-s -w" github.com/gokcehan/lf@latest

- name: Install packages from flatpak
  become: true
  become_user: "{{ user }}"
  community.general.flatpak:
    name:
      - com.discordapp.Discord
      - net.lutris.Lutris
      - io.dbeaver.DBeaverCommunity
      - us.zoom.Zoom
      - io.podman_desktop.PodmanDesktop
    state: present

- name: Set defualt shell to zsh
  command: chsh -s /usr/bin/zsh "{{ user }}"

- name: Link zshrc to home folder
  become: true
  become_user: "{{ user }}"
  shell: ln -sf /home/{{ user }}/.config/zsh/.zshrc /home/{{ user }}/.zshrc

- name: Link zshenv to home folder
  become: true
  become_user: "{{ user }}"
  shell: ln -sf /home/{{ user }}/.config/zsh/.zshenv /home/{{ user }}/.zshenv
